DATABASE_FILE: "thoughts.db"
MAX_DB_SIZE: 1020054732.8
MAX_AUDIO_FILE_SIZE_MB: 25
AUDIO_TRANSCRIPTION_MODEL: "whisper-1"
AUDIO_SILENCE_MIN_LEN_MS: 1000
AUDIO_SILENCE_THRESH_DB: -40
AUDIO_KEEP_SILENCE_MS: 500
AUDIO_FALLBACK_CHUNK_MIN: 10
MAX_TOKENS_FOR_ANALYSIS: 20000
CHUNK_SIZE_TOKENS: 15000

DEFAULT_MODEL: "gpt-4o"
OPENAI_MODELS_LIST:
  - "gpt-4o"
  - "gpt-4o-mini"
  - "gpt-4-turbo"
  - "gpt-4-turbo-preview"
  - "gpt-4"
  - "gpt-5-nano-2025-08-07"
  - "gpt-5-mini-2025-08-07"


TOGETHER_MODELS_LIST:
  - "meta-llama/Llama-3.3-70B-Instruct-Turbo"
  - "meta-llama/Llama-3.1-70B-Instruct-Turbo"
  - "meta-llama/Llama-3.1-8B-Instruct-Turbo"
  - "meta-llama/Llama-3-70b-chat-hf"
  - "Qwen/QwQ-32B-Preview"
  - "Qwen/Qwen2.5-72B-Instruct-Turbo"
  - "Qwen/Qwen2.5-32B-Instruct-Turbo"
  - "Qwen/Qwen2.5-14B-Instruct-Turbo"
  - "Qwen/Qwen2.5-7B-Instruct-Turbo"
  - "Qwen/Qwen1.5-110B-Chat"
  - "mistralai/Mixtral-8x22B-Instruct-v0.1"
  - "mistralai/Mixtral-8x7B-Instruct-v0.1"
  - "mistralai/Mistral-7B-Instruct-v0.3"
  - "WizardLM/WizardLM-13B-V1.2"
  - "togethercomputer/RedPajama-INCITE-7B-Chat"
  - "togethercomputer/alpaca-7b"

PLACEHOLDER_USER_INPUT: "USER_INPUT:"
PLACEHOLDER_DREAMS_THOUGHTS: "INOUT DREAMS/THOUGHTS:"
PLACEHOLDER_DREAMS_CONTENT: "DREAMS TO SUMMARIZE:"
